name: "Copy milestone from issue to pull request"
description: "Copy milestone from issue to pull request"
inputs:
  github-token: # id of input
    description: "Github Token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "git-pull-request"
  color: "green"
