name: 'Copy milestone from issue to pull request'
description: 'Copy milestone from issue to pull request'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'Github Token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'green'
