name: Test copy milestone from issue to pr
on:
  pull_request:
      types:
        - opened
        - edited
        - reopened
jobs:
  test:
    runs-on: ubuntu-latest
    name: test wrokflow
    steps:
      - uses: actions/checkout@v2
      - name: run action
        id: test
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
